@topicId=2
@commentId=1

### 특정 토픽에 대한 코멘트 불러오기(메인)✅
GET http://localhost:8080/comments/{{topicId}}

### 코멘트 기능✅
POST http://localhost:8080/comments/{{topicId}}
Content-Type: application/json

{
  "name": "123",
  "content": "이거 개명작게임임"
}

### 코멘트 좋아요/싫어요 기능✅
POST http://localhost:8080/comments/like/{{commentId}}
Content-Type: application/json

{
  "commentType" : "LIKE"
}

### 코멘트 삭제기능(어드민 전용) : 실패✅
PATCH http://localhost:8080/comments/{{commentId}}

### 특정 토픽에 대한 코멘트 불러오기(메인)✅
GET http://localhost:8080/comments/{{topicId}}