POST http://localhost:8080/topics/admin
Content-Type: application/json

{
  "topicName": "부활",
  "genre" : "NOVEL"
}

###
PATCH http://localhost:8080/topics/admin
Content-Type: application/json

{
  "id" : 1,
  "topicName": "부활",
  "genre" : "NOVEL"
}

###
DELETE http://localhost:8080/topics/admin/{topicId}
Content-Type: application/json

###
GET http://localhost:8080/topics
Content-Type: application/json

###
GET http://localhost:8080/topics/genres?genre=aaa
Content-Type: application/json

###
GET http://localhost:8080/topics/titles?title=aaa
Content-Type: application/json

###
GET http://localhost:8080/topics/{topicId}
Content-Type: application/json
