### 투표(좋아요)✅
@topicId = 2
POST http://localhost:8080/votes/{{topicId}}
Content-Type: application/json

{
  "voteType" : "LIKE"
}

### 투표(싫어요)✅
POST http://localhost:8080/votes/{{topicId}}
Content-Type: application/json

{
  "voteType" : "DISLIKE"
}